export type Folder = {
    id: string;
    name: string;
    type: 'folder';
    parent: string | null;
    modified?: Date;
    created?: Date;
};

export type File = {
    id: string;
    name: string;
    type: 'file';
    parent: string | null;
    url: string;
    size: number;
    modified?: Date;
    created?: Date;
};


export const mockFolders: Folder[] = [
    {
        id: 'root',
        name: 'Root',
        type: 'folder',
        parent: null,
    },
    {
        id: '1',
        name: 'Folder 1',
        type: 'folder',
        parent: 'root',

    },
    {
        id: '2',
        name: 'Folder 2',
        type: 'folder',
        parent: 'root',
    },
    {
        id: '3',
        name: 'Folder 3',
        type: 'folder',
        parent: 'root',
    },
    {
        id: '4',
        name: 'Folder 4',
        type: 'folder',
        parent: '1',
    },
    {
        id: '5',
        name: 'Folder 5',
        type: 'folder',
        parent: '1',
    },
    {
        id: '6',
        name: 'Folder 6',
        type: 'folder',
        parent: '2',
    },
    {
        id: '7',
        name: 'Folder 7',
        type: 'folder',
        parent: '2',
    },
    {
        id: '8',
        name: 'Folder 8',
        type: 'folder',
        parent: '3',
    },
    {
        id: '9',
        name: 'Folder 9',
        type: 'folder',
        parent: '3',
    },
    {
        id: '10',
        name: 'Folder 10',
        type: 'folder',
        parent: '1',
    },
    {
        id: '11',
        name: 'Folder 11',
        type: 'folder',
        parent: '2',
    },
    {
        id: '12',
        name: 'Folder 12',
        type: 'folder',
        parent: '3',
    },
];

export const mockFiles: File[] = [
    {
        id: 'file1',
        name: 'File 1',
        type: 'file',
        parent: '1',
        url: '/files/file1.txt',
        size: 1234,
    },
    {
        id: 'file2',
        name: 'File 2',
        type: 'file',
        parent: '1',
        url: '/files/file2.txt',
        size: 2345,
    },
    {
        id: 'file3',
        name: 'File 3',
        type: 'file',
        parent: '2',
        url: '/files/file3.txt',
        size: 3456,
    },
    {
        id: 'file4',
        name: 'File 4',
        type: 'file',
        parent: '2',
        url: '/files/file4.txt',
        size: 4567,
    },
    {
        id: 'file5',
        name: 'File 5',
        type: 'file',
        parent: '3',
        url: '/files/file5.txt',
        size: 5678,
    },
    {
        id: 'file6',
        name: 'File 6',
        type: 'file',
        parent: '3',
        url: '/files/file6.txt',
        size: 6789,
    },
    {
        id: 'file7',
        name: 'File 7',
        type: 'file',
        parent: '1',
        url: '/files/file7.txt',
        size: 7890,
    },
    {
        id: 'file8',
        name: 'File 8',
        type: 'file',
        parent: '1',
        url: '/files/file8.txt',
        size: 8901,
    },
    {
        id: 'file9',
        name: 'File 9',
        type: 'file',
        parent: '2',
        url: '/files/file9.txt',
        size: 9012,
    },
    {
        id: 'file10',
        name: 'File 10',
        type: 'file',
        parent: '2',
        url: '/files/file10.txt',
        size: 10123,
    },
    {
        id: 'file11',
        name: 'File 11',
        type: 'file',
        parent: '3',
        url: '/files/file11.txt',
        size: 11234,
    },
    {
        id: 'file12',
        name: 'File 12',
        type: 'file',
        parent: '3',
        url: '/files/file12.txt',
        size: 12345,
    },
    {
        id: 'file13',
        name: 'File 13',
        type: 'file',
        parent: '1',
        url: '/files/file13.txt',
        size: 13456,
    },
    {
        id: 'file14',
        name: 'File 14',
        type: 'file',
        parent: '1',
        url: '/files/file14.txt',
        size: 14567,
    },
    {
        id: 'file15',
        name: 'File 15',
        type: 'file',
        parent: '2',
        url: '/files/file15.txt',
        size: 15678,
    },
    {
        id: 'file16',
        name: 'File 16',
        type: 'file',
        parent: '2',
        url: '/files/file16.txt',
        size: 16789,
    },
    {
        id: 'file17',
        name: 'File 17',
        type: 'file',
        parent: '3',
        url: '/files/file17.txt',
        size: 17890,
    },
    {
        id: 'file18',
        name: 'File 18',
        type: 'file',
        parent: '3',
        url: '/files/file18.txt',
        size: 18901,
    },
    {
        id: 'file19',
        name: 'File 19',
        type: 'file',
        parent: '1',
        url: '/files/file19.txt',
        size: 19012,
    },
    {
        id: 'file20',
        name: 'File 20',
        type: 'file',
        parent: '1',
        url: '/files/file20.txt',
        size: 20123,
    },
    {
        id: 'file21',
        name: 'File 21',
        type: 'file',
        parent: 'root',
        url: '/files/file21.txt',
        size: 21234,
    },
    {
        id: 'file22',
        name: 'File 22',
        type: 'file',
        parent: 'root',
        url: '/files/file22.txt',
        size: 22345,
    },
    {
        id: 'file23',
        name: 'File 23',
        type: 'file',
        parent: '4',
        url: '/files/file23.txt',
        size: 3456,
    },
    {
        id: 'file24',
        name: 'File 24',
        type: 'file',
        parent: '5',
        url: '/files/file24.txt',
        size: 4567,
    },
    {
        id: 'file25',
        name: 'File 25',
        type: 'file',
        parent: '6',
        url: '/files/file25.txt',
        size: 5678,
    },
    {
        id: 'file26',
        name: 'File 26',
        type: 'file',
        parent: '7',
        url: '/files/file26.txt',
        size: 6789,
    },
    {
        id: 'file27',
        name: 'File 27',
        type: 'file',
        parent: '8',
        url: '/files/file27.txt',
        size: 7890,
    },
    {
        id: 'file28',
        name: 'File 28',
        type: 'file',
        parent: '9',
        url: '/files/file28.txt',
        size: 8901,
    },
    {
        id: 'file29',
        name: 'File 29',
        type: 'file',
        parent: '10',
        url: '/files/file29.txt',
        size: 9012,
    },
    {
        id: 'file30',
        name: 'File 30',
        type: 'file',
        parent: '11',
        url: '/files/file30.txt',
        size: 10123,
    },
    {
        id: 'file31',
        name: 'File 31',
        type: 'file',
        parent: '12',
        url: '/files/file31.txt',
        size: 11234,
    },
    {
        id: 'file32',
        name: 'File 32',
        type: 'file',
        parent: '4',
        url: '/files/file32.txt',
        size: 12345,
    },
    {
        id: 'file33',
        name: 'File 33',
        type: 'file',
        parent: '5',
        url: '/files/file33.txt',
        size: 13456,
    },
    {
        id: 'file34',
        name: 'File 34',
        type: 'file',
        parent: '6',
        url: '/files/file34.txt',
        size: 14567,
    },
    {
        id: 'file35',
        name: 'File 35',
        type: 'file',
        parent: '7',
        url: '/files/file35.txt',
        size: 15678,
    },
    {
        id: 'file36',
        name: 'File 36',
        type: 'file',
        parent: '8',
        url: '/files/file36.txt',
        size: 16789,
    },
    {
        id: 'file37',
        name: 'File 37',
        type: 'file',
        parent: '9',
        url: '/files/file37.txt',
        size: 17890,
    },
    {
        id: 'file38',
        name: 'File 38',
        type: 'file',
        parent: '10',
        url: '/files/file38.txt',
        size: 18901,
    },
    {
        id: 'file39',
        name: 'File 39',
        type: 'file',
        parent: '11',
        url: '/files/file39.txt',
        size: 19012,
    },
    {
        id: 'file40',
        name: 'File 40',
        type: 'file',
        parent: '12',
        url: '/files/file40.txt',
        size: 20123,
    },
    {
        id: 'file41',
        name: 'File 41',
        type: 'file',
        parent: '4',
        url: '/files/file41.txt',
        size: 21234,
    },
    {
        id: 'file42',
        name: 'File 42',
        type: 'file',
        parent: '5',
        url: '/files/file42.txt',
        size: 22345,
    },
    {
        id: 'file43',
        name: 'File 43',
        type: 'file',
        parent: '6',
        url: '/files/file43.txt',
        size: 23456,
    },
    {
        id: 'file44',
        name: 'File 44',
        type: 'file',
        parent: '7',
        url: '/files/file44.txt',
        size: 24567,
    },
    {
        id: 'file45',
        name: 'File 45',
        type: 'file',
        parent: '8',
        url: '/files/file45.txt',
        size: 25678,
    },
    {
        id: 'file46',
        name: 'File 46',
        type: 'file',
        parent: '9',
        url: '/files/file46.txt',
        size: 26789,
    },
    {
        id: 'file47',
        name: 'File 47',
        type: 'file',
        parent: '10',
        url: '/files/file47.txt',
        size: 27890,
    },
    {
        id: 'file48',
        name: 'File 48',
        type: 'file',
        parent: '11',
        url: '/files/file48.txt',
        size: 28901,
    },
    {
        id: 'file49',
        name: 'File 49',
        type: 'file',
        parent: '12',
        url: '/files/file49.txt',
        size: 29012,
    },
    {
        id: 'file50',
        name: 'File 50',
        type: 'file',
        parent: '4',
        url: '/files/file50.txt',
        size: 30123,
    },
    {
        id: 'file51',
        name: 'File 51',
        type: 'file',
        parent: '5',
        url: '/files/file51.txt',
        size: 31234,
    },
    {
        id: 'file52',
        name: 'File 52',
        type: 'file',
        parent: '6',
        url: '/files/file52.txt',
        size: 32345,
    },
    {
        id: 'file53',
        name: 'File 53',
        type: 'file',
        parent: '7',
        url: '/files/file53.txt',
        size: 33456,
    },
    {
        id: 'file54',
        name: 'File 54',
        type: 'file',
        parent: '8',
        url: '/files/file54.txt',
        size: 34567,
    },
    {
        id: 'file55',
        name: 'File 55',
        type: 'file',
        parent: '9',
        url: '/files/file55.txt',
        size: 35678,
    },
    {
        id: 'file56',
        name: 'File 56',
        type: 'file',
        parent: '10',
        url: '/files/file56.txt',
        size: 36789,
    },
    {
        id: 'file57',
        name: 'File 57',
        type: 'file',
        parent: '11',
        url: '/files/file57.txt',
        size: 37890,
    },
    {
        id: 'file58',
        name: 'File 58',
        type: 'file',
        parent: '12',
        url: '/files/file58.txt',
        size: 38901,
    },
    {
        id: 'file59',
        name: 'File 59',
        type: 'file',
        parent: '4',
        url: '/files/file59.txt',
        size: 39012,
    },
    {
        id: 'file60',
        name: 'File 60',
        type: 'file',
        parent: '5',
        url: '/files/file60.txt',
        size: 40123,
    },
    {
        id: 'file61',
        name: 'File 61',
        type: 'file',
        parent: '6',
        url: '/files/file61.txt',
        size: 41234,
    },
    {
        id: 'file62',
        name: 'File 62',
        type: 'file',
        parent: '7',
        url: '/files/file62.txt',
        size: 42345,
    },
];